meta_product_name: "Contour Golf Limited"
meta_title: "Contour Golf Limited - Golf Course Constructors & Soil Recovery Specialists"
meta_description: "Traditional Golf Course Construction Specialists and Experts in Soil Recovery - Inert Waste Infill Projects. Contour Golf was established in 1993 and specialises in the construction and remodelling of golf courses."
# meta_image: "siteworkr-logo.png"                       # should exist in `app/assets/images/`
# twitter_account: "@siteworkr"

