meta_product_name: "Contour Golf Limited"
meta_title: "Contour Golf Limited - Golf course construction & soil recovery specialists"
meta_description: "Traditional golf course construction specialists with expertise in soil recovery/inert waste infill projects"
# meta_image: "siteworkr-logo.png"                       # should exist in `app/assets/images/`
# twitter_account: "@siteworkr"
